### ISSUE TITLE
html structure

### ISSUE THREAD

**Issue by Rufasa85** [Rufasa85/manatee-jokes-2#2]
## USER STORY 
AS A joke fan
I WANT content on the page
SO THAT i can see the joke

## Acceptance  Criteria
- [x] `<body>` tag contains one `<main>` tag
- [x]  `<h1>` for the manatee joke setup
- [x]  `<h2>` for the punchline
- [x]  `<button id="punchline-btn">` to show punchline
- [x] `<button id="joke-btn">` to show new joke

**Comment by matthewtodor** [comment]
Added ids to the h1 and h2 elements to more easily target them in the javascript.
